### ISSUE TITLE
Compute_template_metrics() TypeError: compute_template_metrics() got an unexpected keyword argument 'include_multi_channel_metrics'

### ISSUE THREAD

**Issue by taningh86** [SpikeInterface/spikeinterface#2390]
I used the following code : 
```
spost.compute_template_metrics(we, load_if_exists= True, metric_names=['peak_to_valley', 'peak_trough_ratio', 'half_width',  
repolarization_slope', 'recovery_slope'], peak_sign= 'neg', upsampling_factor= 10, sparsity= sparsity, include_multi_channel_metrics= False, metrics_kwargs=None)
```
And, it gives the TypeError: compute_template_metrics() got an unexpected keyword argument 'include_multi_channel_metrics'. I get the same error for 'metrics_kwargs' after I omit  'include_multi_channel_metrics' altogether. I know I can pass additional arguments to 'metrics_kwargs' and did try "metrics_kwargs={'recovery_window_ms': 0.7}" but I get the similar type error. 
I am assuming my code is correct here but not sure where is the error originating from. Will appreciate any suggestion or resolution for this error.

Thanks
Jimmy

**Comment by alejoe91** [comment]
Jimmy can you make sure you have version 0.99.1?

**Comment by taningh86** [comment]
I have 0.98.2. I will update now and check if it works. Will update shortly. Thanks Alessio!

**Comment by taningh86** [comment]
It works with the 0.99.1 version.
On a side note, at first I updated to 0.100.0.dev1 version and it was really slow.
